import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


REGIME_ORDER = ["Consolidation", "Bull", "Bear"]
DEFAULT_REGIME_WEIGHTS = {
    "Bull": 0.90,
    "Consolidation": 0.55,
    "Bear": 0.20,
}

DEFAULT_RULES = [
    {
        "priority": 1,
        "trigger_type": "transition",
        "trigger": "Bear -> Bull",
        "target_weight": 1.00,
        "rationale": "Strongest reversal confirmation in transition forward-return analysis.",
    },
    {
        "priority": 2,
        "trigger_type": "transition",
        "trigger": "Bear -> Consolidation",
        "target_weight": 0.60,
        "rationale": "Early base-building zone after a bearish stretch.",
    },
    {
        "priority": 3,
        "trigger_type": "transition",
        "trigger": "Consolidation -> Bull",
        "target_weight": 0.85,
        "rationale": "Bullish breakout from a neutral regime tends to follow through.",
    },
    {
        "priority": 4,
        "trigger_type": "transition",
        "trigger": "Bull -> Consolidation",
        "target_weight": 0.35,
        "rationale": "Trend fatigue; reduce spot exposure rather than chasing.",
    },
    {
        "priority": 5,
        "trigger_type": "transition",
        "trigger": "Bull -> Bear",
        "target_weight": 0.15,
        "rationale": "Defensive reset after a bullish regime breaks down.",
    },
    {
        "priority": 6,
        "trigger_type": "transition",
        "trigger": "Consolidation -> Bear",
        "target_weight": 0.20,
        "rationale": "Weakening structure; keep only a small core allocation.",
    },
    {
        "priority": 7,
        "trigger_type": "regime",
        "trigger": "Bull",
        "target_weight": 0.90,
        "rationale": "Trend-following baseline in confirmed bullish conditions.",
    },
    {
        "priority": 8,
        "trigger_type": "regime",
        "trigger": "Consolidation",
        "target_weight": 0.55,
        "rationale": "Neutral baseline while waiting for the next directional move.",
    },
    {
        "priority": 9,
        "trigger_type": "regime",
        "trigger": "Bear",
        "target_weight": 0.20,
        "rationale": "Defensive baseline; avoid treating every bear bar as a bottom.",
    },
]


def weight_arg(value):
    parsed = float(value)
    if parsed < 0.0 or parsed > 1.0:
        raise argparse.ArgumentTypeError("weight must be between 0.0 and 1.0")
    return parsed


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run a spot BTC backtest driven by regime and transition signals."
    )
    parser.add_argument(
        "--input",
        default="results/regime_predictions_4h.csv",
        help="Path to the regime prediction CSV generated by predict.py",
    )
    parser.add_argument(
        "--datetime-col",
        default="datetime",
        help="Datetime column used by the prediction file",
    )
    parser.add_argument(
        "--open-col",
        default="open",
        help="Open price column used for next-bar execution",
    )
    parser.add_argument(
        "--close-col",
        default="close",
        help="Close price column used for marking equity and buy-and-hold",
    )
    parser.add_argument(
        "--regime-col",
        default="prediction_name",
        help="Column containing regime labels",
    )
    parser.add_argument(
        "--initial-cash",
        type=float,
        default=100000.0,
        help="Starting cash value for the spot backtest",
    )
    parser.add_argument(
        "--fee-rate",
        type=float,
        default=0.0005,
        help="Proportional fee per trade side, e.g. 0.0005 = 5 bps",
    )
    parser.add_argument(
        "--slippage-bps",
        type=float,
        default=10.0,
        help="Execution slippage in basis points applied on each trade",
    )
    parser.add_argument(
        "--rebalance-threshold",
        type=float,
        default=0.20,
        help="Minimum weight gap required before scheduling a rebalance",
    )
    parser.add_argument(
        "--max-weight-step",
        type=float,
        default=0.25,
        help="Maximum weight change per rebalance event",
    )
    parser.add_argument(
        "--transition-cooldown-bars",
        type=int,
        default=6,
        help="Number of bars to pause new rebalances after a transition-triggered trade",
    )
    parser.add_argument(
        "--min-regime-bars",
        type=int,
        default=6,
        help="Minimum consecutive bars a regime must persist before its transition becomes effective for rebalancing.",
    )
    parser.add_argument(
        "--confidence-threshold",
        type=float,
        default=None,
        help="Minimum posterior probability required to confirm a regime signal. When omitted, all signals are used.",
    )
    parser.add_argument(
        "--strategy-preset",
        choices=[
            "default",
            "regime_baseline",
            "no_transition",
            "transition_confirmed",
            "custom_weights",
        ],
        default="default",
        help="Strategy rule preset. default keeps the built-in transition/regime rules.",
    )
    parser.add_argument(
        "--bull-weight",
        type=weight_arg,
        default=DEFAULT_REGIME_WEIGHTS["Bull"],
        help="Target spot weight for Bull in non-default/custom presets.",
    )
    parser.add_argument(
        "--consolidation-weight",
        type=weight_arg,
        default=DEFAULT_REGIME_WEIGHTS["Consolidation"],
        help="Target spot weight for Consolidation in non-default/custom presets.",
    )
    parser.add_argument(
        "--bear-weight",
        type=weight_arg,
        default=DEFAULT_REGIME_WEIGHTS["Bear"],
        help="Target spot weight for Bear in non-default/custom presets.",
    )
    parser.add_argument(
        "--start-date",
        default=None,
        help="Optional inclusive start date filter, e.g. 2022-01-01",
    )
    parser.add_argument(
        "--end-date",
        default=None,
        help="Optional inclusive end date filter, e.g. 2025-12-31",
    )
    parser.add_argument(
        "--summary-output",
        default="results/backtest_summary.csv",
        help="Path to save the summary metrics CSV",
    )
    parser.add_argument(
        "--trades-output",
        default="results/backtest_trades.csv",
        help="Path to save the executed trades CSV",
    )
    parser.add_argument(
        "--equity-output",
        default="results/backtest_equity_curve.csv",
        help="Path to save the equity-curve CSV",
    )
    parser.add_argument(
        "--rules-output",
        default="results/spot_strategy_rules.csv",
        help="Path to save the default strategy rule table",
    )
    parser.add_argument(
        "--plot-output",
        default="results/backtest_equity_curve.png",
        help="Path to save the equity and allocation chart",
    )
    parser.add_argument(
        "--dca-monthly-investment",
        type=float,
        default=None,
        help="Fixed monthly DCA notional. When omitted, initial cash is split evenly across all months in the test range.",
    )
    parser.add_argument(
        "--dca-external-cash",
        type=float,
        default=None,
        help="Monthly external cash injected for DCA benchmark. When set, each month a fresh cash amount is added (simulates real-life recurring investment). Overrides --dca-monthly-investment.",
    )
    return parser.parse_args()


def ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)


def load_prediction_frame(path):
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Prediction file not found: {path}. Run predict.py first or pass --input."
        )
    return pd.read_csv(path)


def build_month_index(df, datetime_col):
    datetimes = pd.to_datetime(df[datetime_col])
    if datetimes.dt.tz is not None:
        datetimes = datetimes.dt.tz_localize(None)
    return datetimes.dt.to_period("M")


def prepare_frame(df, args):
    required_cols = [args.datetime_col, args.open_col, args.close_col, args.regime_col]
    optional_cols = ["prob_consolidation", "prob_bull", "prob_bear"]
    missing = [col for col in required_cols if col not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {', '.join(missing)}")

    frame = df.copy()
    frame[args.datetime_col] = pd.to_datetime(frame[args.datetime_col], errors="coerce").dt.tz_localize("UTC").dt.tz_convert("Asia/Taipei")
    frame = frame.dropna(subset=[args.datetime_col]).sort_values(args.datetime_col).reset_index(drop=True)

    if args.start_date:
        frame = frame.loc[frame[args.datetime_col] >= pd.to_datetime(args.start_date).tz_localize("Asia/Taipei")].copy()
    if args.end_date:
        frame = frame.loc[frame[args.datetime_col] <= pd.to_datetime(args.end_date).tz_localize("Asia/Taipei")].copy()

    if len(frame) < 3:
        raise ValueError("Need at least three rows after filtering to run the backtest.")

    for col in optional_cols:
        if col not in frame.columns:
            frame[col] = np.nan

    frame["prev_regime"] = frame[args.regime_col].shift(1)
    frame["transition"] = np.where(
        frame["prev_regime"].notna(),
        frame["prev_regime"] + " -> " + frame[args.regime_col],
        "START",
    )
    return frame.reset_index(drop=True)


def infer_bars_per_day(df, datetime_col):
    dt = pd.to_datetime(df[datetime_col], errors="coerce").dropna().sort_values()
    if len(dt) < 2:
        raise ValueError("Need at least two valid datetime rows to infer bars per day.")

    median_delta = dt.diff().dropna().median()
    if pd.isna(median_delta) or median_delta.total_seconds() <= 0:
        raise ValueError("Failed to infer a positive median bar interval.")
    return 86400.0 / median_delta.total_seconds()


def compute_dca_schedule(df, datetime_col, initial_cash, fee_rate, dca_monthly_investment, dca_external_cash=None):
    month_key = build_month_index(df, datetime_col)
    first_rows = month_key.groupby(month_key).head(1).index.to_list()
    n_months = len(first_rows)
    if n_months == 0:
        return {}, 0.0, False

    if dca_external_cash is not None:
        monthly_notional = float(dca_external_cash)
        schedule = {idx: monthly_notional for idx in first_rows}
        return schedule, monthly_notional, True
    elif dca_monthly_investment is not None:
        monthly_notional = float(dca_monthly_investment)
    else:
        monthly_notional = initial_cash / n_months

    if monthly_notional <= 0:
        return {}, 0.0, False

    schedule = {}
    remaining_cash = float(initial_cash)
    for idx in first_rows:
        affordable = remaining_cash / (1.0 + fee_rate)
        trade_notional = min(monthly_notional, affordable)
        if trade_notional <= 0:
            break
        schedule[idx] = trade_notional
        remaining_cash -= trade_notional * (1.0 + fee_rate)

    return schedule, monthly_notional, False


def execute_spot_buy(cash, btc, open_price, trade_notional, fee_rate, slippage_bps):
    if trade_notional <= 0 or open_price <= 0:
        return cash, btc, None

    exec_price = open_price * (1.0 + slippage_bps / 10000.0)
    btc_delta = trade_notional / exec_price
    fee = trade_notional * fee_rate
    cash_after = cash - trade_notional - fee
    btc_after = btc + btc_delta

    trade = {
        "trade_notional": trade_notional,
        "exec_price": exec_price,
        "btc_delta": btc_delta,
        "fee_paid": fee,
    }
    return cash_after, btc_after, trade


def build_regime_rules(weights, start_priority=1):
    rows = []
    for offset, regime_name in enumerate(["Bull", "Consolidation", "Bear"]):
        rows.append(
            {
                "priority": start_priority + offset,
                "trigger_type": "regime",
                "trigger": regime_name,
                "target_weight": float(weights[regime_name]),
                "rationale": f"Regime-only target for {regime_name}.",
            }
        )
    return rows


def get_regime_weights(args):
    return {
        "Bull": float(getattr(args, "bull_weight", DEFAULT_REGIME_WEIGHTS["Bull"])),
        "Consolidation": float(
            getattr(args, "consolidation_weight", DEFAULT_REGIME_WEIGHTS["Consolidation"])
        ),
        "Bear": float(getattr(args, "bear_weight", DEFAULT_REGIME_WEIGHTS["Bear"])),
    }


def build_strategy_rules(args):
    custom_rules = getattr(args, "custom_rules", None)
    if custom_rules is not None:
        return [dict(rule) for rule in custom_rules]

    preset = getattr(args, "strategy_preset", "default")
    weights = get_regime_weights(args)

    if preset == "default":
        return [dict(rule) for rule in DEFAULT_RULES]

    if preset in {"regime_baseline", "no_transition", "custom_weights"}:
        return build_regime_rules(weights)

    if preset == "transition_confirmed":
        transition_rules = [
            dict(rule) for rule in DEFAULT_RULES if rule["trigger_type"] == "transition"
        ]
        transition_count = len(transition_rules)
        return transition_rules + build_regime_rules(
            weights,
            start_priority=transition_count + 1,
        )

    raise ValueError(f"Unknown strategy preset: {preset}")


def build_rules_table(args=None):
    if args is None:
        return pd.DataFrame(DEFAULT_RULES)
    return pd.DataFrame(build_strategy_rules(args))


def determine_target_weight(regime, transition, rules):
    for rule in rules:
        if rule["trigger_type"] == "transition" and rule["trigger"] == transition:
            return float(rule["target_weight"]), rule["trigger"]

    for rule in rules:
        if rule["trigger_type"] == "regime" and rule["trigger"] == regime:
            return float(rule["target_weight"]), rule["trigger"]

    raise ValueError(f"No strategy rule matched transition={transition} regime={regime}")


def clamp(value, low, high):
    return max(low, min(high, value))


def compute_schedule_target(current_weight, desired_weight, threshold, max_step):
    gap = desired_weight - current_weight
    if abs(gap) < threshold:
        return current_weight, False

    step = np.sign(gap) * min(abs(gap), max_step)
    target = clamp(current_weight + step, 0.0, 1.0)
    return target, True


def execute_rebalance(cash, btc, mark_price, open_price, target_weight, fee_rate, slippage_bps):
    if mark_price <= 0 or open_price <= 0:
        return cash, btc, None

    current_equity = cash + btc * mark_price
    if current_equity <= 0:
        return cash, btc, None

    current_weight = (btc * mark_price) / current_equity if current_equity > 0 else 0.0
    slippage = slippage_bps / 10000.0
    target_weight = clamp(target_weight, 0.0, 1.0)
    desired_value = target_weight * current_equity
    current_value = btc * mark_price
    diff_value = desired_value - current_value

    if abs(diff_value) < 1e-9:
        return cash, btc, None

    if diff_value > 0:
        side = "BUY"
        exec_price = open_price * (1.0 + slippage)
        trade_notional = min(diff_value, cash / (1.0 + fee_rate))
        if trade_notional <= 0:
            return cash, btc, None
        btc_delta = trade_notional / exec_price
        fee = trade_notional * fee_rate
        cash_after = cash - trade_notional - fee
        btc_after = btc + btc_delta
    else:
        side = "SELL"
        exec_price = open_price * (1.0 - slippage)
        max_notional = btc * exec_price
        trade_notional = min(-diff_value, max_notional)
        if trade_notional <= 0:
            return cash, btc, None
        btc_delta = trade_notional / exec_price
        fee = trade_notional * fee_rate
        cash_after = cash + trade_notional - fee
        btc_after = btc - btc_delta

    trade = {
        "side": side,
        "exec_price": exec_price,
        "trade_notional": trade_notional,
        "btc_delta": btc_delta if side == "BUY" else -btc_delta,
        "fee_paid": fee,
        "pre_trade_equity": current_equity,
        "pre_trade_weight": current_weight,
    }
    return cash_after, btc_after, trade


def run_backtest(df, args):
    rules = build_strategy_rules(args)
    cash = float(args.initial_cash)
    btc = 0.0
    pending_order = None
    transition_cooldown_remaining = 0

    confirmed_regime = None
    consecutive_regime_bars = 0
    current_run_regime = None

    dca_cash = float(args.initial_cash) if not args.dca_external_cash else 0.0
    dca_btc = 0.0
    dca_cumulative_invested = float(args.initial_cash) if not args.dca_external_cash else 0.0
    dca_schedule, dca_monthly_notional, dca_uses_external = compute_dca_schedule(
        df=df,
        datetime_col=args.datetime_col,
        initial_cash=args.initial_cash,
        fee_rate=args.fee_rate,
        dca_monthly_investment=args.dca_monthly_investment,
        dca_external_cash=args.dca_external_cash,
    )

    equity_rows = []
    trade_rows = []

    for idx, row in df.iterrows():
        dt = row[args.datetime_col]
        open_price = float(row[args.open_col])
        close_price = float(row[args.close_col])
        regime = row[args.regime_col]
        raw_transition = row["transition"]

        dca_trade = None
        if idx in dca_schedule:
            if dca_uses_external:
                dca_cash += dca_schedule[idx]
                dca_cumulative_invested += dca_schedule[idx]
            dca_cash, dca_btc, dca_trade = execute_spot_buy(
                cash=dca_cash,
                btc=dca_btc,
                open_price=open_price,
                trade_notional=dca_schedule[idx],
                fee_rate=args.fee_rate,
                slippage_bps=args.slippage_bps,
            )

        executed_trade = None
        if pending_order is not None:
            cash, btc, trade = execute_rebalance(
                cash=cash,
                btc=btc,
                mark_price=float(pending_order["mark_price"]),
                open_price=open_price,
                target_weight=float(pending_order["target_weight"]),
                fee_rate=args.fee_rate,
                slippage_bps=args.slippage_bps,
            )
            if trade is not None:
                executed_trade = {
                    "datetime": dt,
                    "signal_datetime": pending_order["signal_datetime"],
                    "trigger": pending_order["trigger"],
                    "trigger_type": pending_order["trigger_type"],
                    "signal_regime": pending_order["signal_regime"],
                    "signal_transition": pending_order["signal_transition"],
                    "desired_weight": pending_order["desired_weight"],
                    "scheduled_target_weight": pending_order["target_weight"],
                    **trade,
                }
                trade_rows.append(executed_trade)
                if (
                    pending_order["trigger_type"] == "transition"
                    and args.transition_cooldown_bars > 0
                ):
                    transition_cooldown_remaining = args.transition_cooldown_bars + 1
            pending_order = None

        if regime == current_run_regime:
            consecutive_regime_bars += 1
        else:
            consecutive_regime_bars = 1
            current_run_regime = regime

        previous_confirmed_regime = confirmed_regime
        if confirmed_regime is None:
            confirmed_regime = regime
        elif regime != confirmed_regime and consecutive_regime_bars >= args.min_regime_bars:
            confirmed_regime = regime

        if previous_confirmed_regime is None:
            confirmed_transition = "START"
        elif confirmed_regime != previous_confirmed_regime:
            confirmed_transition = f"{previous_confirmed_regime} -> {confirmed_regime}"
        else:
            confirmed_transition = confirmed_regime

        equity = cash + btc * close_price
        spot_weight = (btc * close_price) / equity if equity > 0 else 0.0
        desired_weight, trigger = determine_target_weight(
            confirmed_regime,
            confirmed_transition,
            rules,
        )
        trigger_type = "transition" if " -> " in trigger else "regime"

        next_target_weight = np.nan
        scheduled = False
        if idx < len(df) - 1:
            if transition_cooldown_remaining <= 0:
                effective_desired = desired_weight
                if args.confidence_threshold is not None:
                    max_prob = max(
                        row.get("prob_bull", 0.0) or 0.0,
                        row.get("prob_bear", 0.0) or 0.0,
                        row.get("prob_consolidation", 0.0) or 0.0,
                    )
                    if max_prob < args.confidence_threshold:
                        effective_desired = spot_weight

                next_target_weight, scheduled = compute_schedule_target(
                    current_weight=spot_weight,
                    desired_weight=effective_desired,
                    threshold=args.rebalance_threshold,
                    max_step=args.max_weight_step,
                )
                if scheduled:
                    pending_order = {
                        "signal_datetime": dt,
                        "mark_price": close_price,
                        "target_weight": float(next_target_weight),
                        "desired_weight": float(desired_weight),
                        "trigger": trigger,
                        "trigger_type": trigger_type,
                        "signal_regime": confirmed_regime,
                        "signal_transition": confirmed_transition,
                    }

        equity_rows.append(
            {
                "datetime": dt,
                "close": close_price,
                "regime": regime,
                "confirmed_regime": confirmed_regime,
                "consecutive_regime_bars": consecutive_regime_bars,
                "transition": raw_transition,
                "confirmed_transition": confirmed_transition,
                "trigger_used": trigger,
                "trigger_type_used": trigger_type,
                "desired_spot_weight": desired_weight,
                "scheduled_target_weight": next_target_weight if scheduled else np.nan,
                "cash": cash,
                "btc_units": btc,
                "spot_weight": spot_weight,
                "equity": equity,
                "buy_hold_equity": args.initial_cash * (close_price / float(df[args.close_col].iloc[0])),
                "dca_cash": dca_cash,
                "dca_btc_units": dca_btc,
                "dca_equity": dca_cash + dca_btc * close_price,
                "dca_cumulative_invested": dca_cumulative_invested,
                "dca_trade_notional": dca_trade["trade_notional"] if dca_trade else 0.0,
                "dca_fee_paid": dca_trade["fee_paid"] if dca_trade else 0.0,
                "dca_monthly_notional": dca_monthly_notional,
                "transition_cooldown_remaining": transition_cooldown_remaining,
                "executed_trade_side": executed_trade["side"] if executed_trade else "",
                "executed_trade_notional": executed_trade["trade_notional"] if executed_trade else 0.0,
                "executed_fee_paid": executed_trade["fee_paid"] if executed_trade else 0.0,
                "prob_consolidation": row.get("prob_consolidation", np.nan),
                "prob_bull": row.get("prob_bull", np.nan),
                "prob_bear": row.get("prob_bear", np.nan),
            }
        )

        if transition_cooldown_remaining > 0:
            transition_cooldown_remaining -= 1

    equity_df = pd.DataFrame(equity_rows)
    trades_df = pd.DataFrame(trade_rows)
    return equity_df, trades_df


def compute_performance_metrics(equity_df, trades_df, initial_cash, bars_per_day, args):
    df = equity_df.copy()
    df["strategy_return"] = df["equity"].pct_change().fillna(0.0)
    df["buy_hold_equity"] = df["buy_hold_equity"]
    df["buy_hold_return"] = df["buy_hold_equity"].pct_change().fillna(0.0)
    df["dca_return"] = df["dca_equity"].pct_change().fillna(0.0)

    years = max((df["datetime"].iloc[-1] - df["datetime"].iloc[0]).total_seconds() / (86400.0 * 365.0), 1e-9)
    periods_per_year = bars_per_day * 365.0

    strategy_total_return = df["equity"].iloc[-1] / initial_cash - 1.0
    buy_hold_total_return = df["buy_hold_equity"].iloc[-1] / initial_cash - 1.0
    dca_cumulative_invested = float(df["dca_cumulative_invested"].iloc[-1])
    dca_uses_external = args.dca_external_cash is not None
    if dca_uses_external and dca_cumulative_invested > 0:
        dca_total_return = df["dca_equity"].iloc[-1] / dca_cumulative_invested - 1.0
    else:
        dca_total_return = df["dca_equity"].iloc[-1] / initial_cash - 1.0

    strategy_cagr = (df["equity"].iloc[-1] / initial_cash) ** (1.0 / years) - 1.0
    buy_hold_cagr = (df["buy_hold_equity"].iloc[-1] / initial_cash) ** (1.0 / years) - 1.0
    if dca_uses_external and dca_cumulative_invested > 0:
        dca_cagr = (df["dca_equity"].iloc[-1] / dca_cumulative_invested) ** (1.0 / years) - 1.0
    else:
        dca_cagr = (df["dca_equity"].iloc[-1] / initial_cash) ** (1.0 / years) - 1.0

    strategy_running_peak = df["equity"].cummax()
    buy_hold_running_peak = df["buy_hold_equity"].cummax()
    dca_running_peak = df["dca_equity"].cummax()
    strategy_drawdown = df["equity"] / strategy_running_peak - 1.0
    buy_hold_drawdown = df["buy_hold_equity"] / buy_hold_running_peak - 1.0
    dca_drawdown = df["dca_equity"] / dca_running_peak - 1.0

    strategy_vol = df["strategy_return"].std() * np.sqrt(periods_per_year)
    buy_hold_vol = df["buy_hold_return"].std() * np.sqrt(periods_per_year)
    dca_vol = df["dca_return"].std() * np.sqrt(periods_per_year)

    strategy_sharpe = (
        df["strategy_return"].mean() / df["strategy_return"].std() * np.sqrt(periods_per_year)
        if df["strategy_return"].std() > 0
        else np.nan
    )
    buy_hold_sharpe = (
        df["buy_hold_return"].mean() / df["buy_hold_return"].std() * np.sqrt(periods_per_year)
        if df["buy_hold_return"].std() > 0
        else np.nan
    )
    dca_sharpe = (
        df["dca_return"].mean() / df["dca_return"].std() * np.sqrt(periods_per_year)
        if df["dca_return"].std() > 0
        else np.nan
    )

    total_fees = float(trades_df["fee_paid"].sum()) if not trades_df.empty else 0.0
    total_turnover = float(trades_df["trade_notional"].sum()) if not trades_df.empty else 0.0
    dca_total_fees = float(df["dca_fee_paid"].sum())
    dca_trade_count = int((df["dca_trade_notional"] > 0).sum())

    summary = pd.DataFrame(
        [
            {"metric": "start_datetime", "value": df["datetime"].iloc[0].tz_localize(None).strftime("%Y-%m-%d %H:%M:%S")},
            {"metric": "end_datetime", "value": df["datetime"].iloc[-1].tz_localize(None).strftime("%Y-%m-%d %H:%M:%S")},
            {"metric": "bars_per_day", "value": bars_per_day},
            {"metric": "years", "value": years},
            {"metric": "initial_cash", "value": initial_cash},
            {"metric": "strategy_preset", "value": getattr(args, "strategy_preset", "default")},
            {"metric": "bull_weight", "value": float(getattr(args, "bull_weight", DEFAULT_REGIME_WEIGHTS["Bull"]))},
            {"metric": "consolidation_weight", "value": float(getattr(args, "consolidation_weight", DEFAULT_REGIME_WEIGHTS["Consolidation"]))},
            {"metric": "bear_weight", "value": float(getattr(args, "bear_weight", DEFAULT_REGIME_WEIGHTS["Bear"]))},
            {"metric": "final_equity_regime", "value": float(df["equity"].iloc[-1])},
            {"metric": "final_equity_buy_hold", "value": float(df["buy_hold_equity"].iloc[-1])},
            {"metric": "final_equity_dca", "value": float(df["dca_equity"].iloc[-1])},
            {"metric": "total_return_regime", "value": float(strategy_total_return)},
            {"metric": "total_return_buy_hold", "value": float(buy_hold_total_return)},
            {"metric": "total_return_dca", "value": float(dca_total_return)},
            {"metric": "cagr_regime", "value": float(strategy_cagr)},
            {"metric": "cagr_buy_hold", "value": float(buy_hold_cagr)},
            {"metric": "cagr_dca", "value": float(dca_cagr)},
            {"metric": "max_drawdown_regime", "value": float(strategy_drawdown.min())},
            {"metric": "max_drawdown_buy_hold", "value": float(buy_hold_drawdown.min())},
            {"metric": "max_drawdown_dca", "value": float(dca_drawdown.min())},
            {"metric": "annual_volatility_regime", "value": float(strategy_vol)},
            {"metric": "annual_volatility_buy_hold", "value": float(buy_hold_vol)},
            {"metric": "annual_volatility_dca", "value": float(dca_vol)},
            {"metric": "sharpe_regime", "value": float(strategy_sharpe)},
            {"metric": "sharpe_buy_hold", "value": float(buy_hold_sharpe)},
            {"metric": "sharpe_dca", "value": float(dca_sharpe)},
            {"metric": "trade_count", "value": int(len(trades_df))},
            {
                "metric": "transition_triggered_trade_count",
                "value": int((trades_df["trigger_type"] == "transition").sum()) if not trades_df.empty else 0,
            },
            {"metric": "dca_trade_count", "value": dca_trade_count},
            {"metric": "total_turnover", "value": total_turnover},
            {"metric": "total_fees_paid", "value": total_fees},
            {"metric": "dca_total_fees_paid", "value": dca_total_fees},
            {"metric": "dca_monthly_notional", "value": float(df["dca_monthly_notional"].iloc[0])},
            {"metric": "dca_cumulative_invested", "value": dca_cumulative_invested},
            {"metric": "dca_uses_external_cash", "value": dca_uses_external},
            {"metric": "avg_spot_weight", "value": float(df["spot_weight"].mean())},
            {"metric": "rebalance_threshold", "value": float(args.rebalance_threshold)},
            {"metric": "transition_cooldown_bars", "value": int(args.transition_cooldown_bars)},
            {"metric": "min_regime_bars", "value": int(args.min_regime_bars)},
        ]
    )
    return summary, df


def save_outputs(summary_df, trades_df, equity_df, rules_df, args):
    for path in [
        args.summary_output,
        args.trades_output,
        args.equity_output,
        args.rules_output,
    ]:
        ensure_parent_dir(path)

    summary_df.to_csv(args.summary_output, index=False)
    trades_df.to_csv(args.trades_output, index=False)
    equity_df.to_csv(args.equity_output, index=False)
    rules_df.to_csv(args.rules_output, index=False)


def plot_results(equity_df, plot_output):
    ensure_parent_dir(plot_output)

    fig, axes = plt.subplots(2, 1, figsize=(14, 8), sharex=True)

    axes[0].plot(equity_df["datetime"], equity_df["equity"], label="Regime-Driven", color="#0B3D20", linewidth=1.8)
    axes[0].plot(
        equity_df["datetime"],
        equity_df["buy_hold_equity"],
        label="Buy & Hold",
        color="#8B0000",
        linewidth=1.3,
        alpha=0.85,
    )
    axes[0].plot(
        equity_df["datetime"],
        equity_df["dca_equity"],
        label="Monthly DCA",
        color="#6B4EFF",
        linewidth=1.3,
        alpha=0.9,
    )
    axes[0].set_title("Regime-Driven Strategy Equity Curve")
    axes[0].set_ylabel("Equity")
    axes[0].grid(True, axis="y", alpha=0.25)
    axes[0].legend(loc="upper left")

    axes[1].plot(
        equity_df["datetime"],
        equity_df["spot_weight"],
        label="Actual spot weight",
        color="#1F4E79",
        linewidth=1.4,
    )
    axes[1].plot(
        equity_df["datetime"],
        equity_df["desired_spot_weight"],
        label="Desired spot weight",
        color="#9A6700",
        linewidth=1.0,
        alpha=0.8,
    )
    axes[1].set_title("Spot Allocation Through Time")
    axes[1].set_ylabel("Weight")
    axes[1].set_xlabel("Datetime")
    axes[1].set_ylim(-0.02, 1.02)
    axes[1].grid(True, axis="y", alpha=0.25)
    axes[1].legend(loc="upper left")

    plt.tight_layout()
    plt.savefig(plot_output, dpi=150, bbox_inches="tight")
    plt.close()


def print_rules_table(rules_df):
    print("\n" + "=" * 80)
    print("Regime-Driven Strategy Rule Table")
    print("=" * 80)
    for _, row in rules_df.sort_values("priority").iterrows():
        print(
            f"{int(row['priority']):>2d}. {row['trigger_type']:10s} {row['trigger']:>24s} "
            f"-> target spot {row['target_weight'] * 100:>5.1f}%"
        )


def print_summary(summary_df):
    summary = dict(zip(summary_df["metric"], summary_df["value"]))

    print("\n" + "=" * 80)
    print("Backtest Summary")
    print("=" * 80)
    print(f"Period: {summary['start_datetime']} -> {summary['end_datetime']}")
    print(f"Regime-Driven final equity:${float(summary['final_equity_regime']):,.2f}")
    print(f"Buy & Hold final equity: ${float(summary['final_equity_buy_hold']):,.2f}")
    print(f"Monthly DCA final equity:${float(summary['final_equity_dca']):,.2f}")
    print(f"DCA cumulative invested: ${float(summary['dca_cumulative_invested']):,.2f}")
    print(f"DCA uses external cash:   {summary['dca_uses_external_cash']}")
    print(f"Regime-Driven total return:{float(summary['total_return_regime']) * 100:,.2f}%")
    print(f"Buy & Hold total return: {float(summary['total_return_buy_hold']) * 100:,.2f}%")
    print(f"Monthly DCA total return:{float(summary['total_return_dca']) * 100:,.2f}%")
    print(f"Regime-Driven CAGR:      {float(summary['cagr_regime']) * 100:,.2f}%")
    print(f"Buy & Hold CAGR:        {float(summary['cagr_buy_hold']) * 100:,.2f}%")
    print(f"Monthly DCA CAGR:       {float(summary['cagr_dca']) * 100:,.2f}%")
    print(f"Regime-Driven max DD:    {float(summary['max_drawdown_regime']) * 100:,.2f}%")
    print(f"Buy & Hold max drawdown:{float(summary['max_drawdown_buy_hold']) * 100:,.2f}%")
    print(f"Monthly DCA max DD:     {float(summary['max_drawdown_dca']) * 100:,.2f}%")
    print(f"Regime-Driven Sharpe:    {float(summary['sharpe_regime']):,.2f}")
    print(f"Buy & Hold Sharpe:      {float(summary['sharpe_buy_hold']):,.2f}")
    print(f"Monthly DCA Sharpe:     {float(summary['sharpe_dca']):,.2f}")
    print(f"Trade count:             {int(float(summary['trade_count']))}")
    print(f"Transition trades:       {int(float(summary['transition_triggered_trade_count']))}")
    print(f"DCA trade count:         {int(float(summary['dca_trade_count']))}")
    print(f"Total turnover:          ${float(summary['total_turnover']):,.2f}")
    print(f"Total fees paid:         ${float(summary['total_fees_paid']):,.2f}")
    print(f"DCA total fees paid:     ${float(summary['dca_total_fees_paid']):,.2f}")
    print(f"DCA monthly notional:    ${float(summary['dca_monthly_notional']):,.2f}")
    print(f"Average spot weight:     {float(summary['avg_spot_weight']) * 100:,.1f}%")
    print(f"Rebalance threshold:     {float(summary['rebalance_threshold']) * 100:,.1f}%")
    print(f"Transition cooldown:     {int(float(summary['transition_cooldown_bars']))} bars")


def main():
    args = parse_args()
    raw_df = load_prediction_frame(args.input)
    df = prepare_frame(raw_df, args)
    bars_per_day = infer_bars_per_day(df, args.datetime_col)

    rules_df = build_rules_table(args)
    equity_df, trades_df = run_backtest(df, args)
    summary_df, equity_df = compute_performance_metrics(
        equity_df=equity_df,
        trades_df=trades_df,
        initial_cash=args.initial_cash,
        bars_per_day=bars_per_day,
        args=args,
    )

    save_outputs(summary_df, trades_df, equity_df, rules_df, args)
    plot_results(equity_df, args.plot_output)

    print_rules_table(rules_df)
    print_summary(summary_df)
    print(f"\nSaved summary CSV to {args.summary_output}")
    print(f"Saved trades CSV to {args.trades_output}")
    print(f"Saved equity CSV to {args.equity_output}")
    print(f"Saved rule table to {args.rules_output}")
    print(f"Saved plot to {args.plot_output}")


if __name__ == "__main__":
    main()
