import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns


REGIME_ORDER = ["Consolidation", "Bull", "Bear"]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Analyze forward returns by regime or by regime transition events."
    )
    parser.add_argument(
        "--mode",
        choices=["regime", "transition"],
        default="transition",
        help="Analysis mode: baseline regime view or transition-event view",
    )
    parser.add_argument(
        "--input",
        default="results/regime_predictions_4h.csv",
        help="Path to the regime prediction CSV generated by predict.py",
    )
    parser.add_argument(
        "--datetime-col",
        default="datetime",
        help="Datetime column used to infer bar frequency",
    )
    parser.add_argument(
        "--price-col",
        default="close",
        help="Price column used to compute forward returns",
    )
    parser.add_argument(
        "--regime-col",
        default="prediction_name",
        help="Column containing regime labels",
    )
    parser.add_argument(
        "--horizons",
        nargs="+",
        type=int,
        default=[7, 30, 90],
        help="Forward return horizons in calendar days",
    )
    parser.add_argument(
        "--bars-per-day",
        type=float,
        default=None,
        help="Override inferred bars-per-day, useful when datetime inference is unavailable",
    )
    parser.add_argument(
        "--include-self-transitions",
        action="store_true",
        help="Include A -> A rows in transition mode",
    )
    parser.add_argument(
        "--output-prefix",
        default=None,
        help="Optional prefix for output files; mode-specific defaults are used when omitted",
    )
    return parser.parse_args()


def ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)


def resolve_output_paths(mode, output_prefix):
    prefix = output_prefix or f"results/{mode}_forward_returns"
    return {
        "summary": f"{prefix}_summary.csv",
        "detail": f"{prefix}_detail.csv",
        "plot": f"{prefix}.png",
    }


def load_prediction_frame(path):
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Prediction file not found: {path}. Run predict.py first or pass --input."
        )
    return pd.read_csv(path)


def infer_bars_per_day(df, datetime_col):
    if datetime_col not in df.columns:
        raise ValueError(
            f"Column '{datetime_col}' not found. Pass --bars-per-day explicitly."
        )

    dt = pd.to_datetime(df[datetime_col], errors="coerce").dropna().sort_values()
    if len(dt) < 2:
        raise ValueError("Need at least two valid datetime rows to infer bars per day.")

    median_delta = dt.diff().dropna().median()
    if pd.isna(median_delta) or median_delta.total_seconds() <= 0:
        raise ValueError("Failed to infer a positive median bar interval.")

    bars_per_day = 86400.0 / median_delta.total_seconds()
    if bars_per_day <= 0:
        raise ValueError("Inferred bars-per-day is not positive.")
    return bars_per_day


def add_forward_return_columns(df, price_col, horizons, bars_per_day):
    enriched = df.copy()
    bar_lookup = {}

    for horizon in horizons:
        bars = max(1, int(round(horizon * bars_per_day)))
        col = f"forward_return_{horizon}d"
        enriched[col] = enriched[price_col].shift(-bars) / enriched[price_col] - 1.0
        bar_lookup[horizon] = bars

    return enriched, bar_lookup


def build_regime_summary(df, regime_col, horizons):
    rows = []
    regimes = [name for name in REGIME_ORDER if name in df[regime_col].dropna().unique()]
    extras = sorted(name for name in df[regime_col].dropna().unique() if name not in REGIME_ORDER)
    regimes.extend(extras)

    for regime_name in ["All"] + regimes:
        data = df if regime_name == "All" else df.loc[df[regime_col] == regime_name]
        for horizon in horizons:
            col = f"forward_return_{horizon}d"
            series = data[col].dropna()
            rows.append(
                {
                    "group": regime_name,
                    "mode": "regime",
                    "horizon_days": horizon,
                    "samples": int(series.shape[0]),
                    "mean_return": float(series.mean()) if len(series) else np.nan,
                    "median_return": float(series.median()) if len(series) else np.nan,
                    "std_return": float(series.std()) if len(series) else np.nan,
                    "win_rate": float((series > 0).mean()) if len(series) else np.nan,
                    "q25_return": float(series.quantile(0.25)) if len(series) else np.nan,
                    "q75_return": float(series.quantile(0.75)) if len(series) else np.nan,
                    "from_regime": regime_name,
                    "to_regime": "",
                    "transition": "",
                }
            )

    summary = pd.DataFrame(rows)
    rank = {"All": -1, **{name: idx for idx, name in enumerate(REGIME_ORDER)}}
    summary["_group_rank"] = summary["group"].map(lambda x: rank.get(x, 999))
    summary = summary.sort_values(["_group_rank", "group", "horizon_days"]).drop(columns="_group_rank")
    return summary.reset_index(drop=True)


def build_transition_events(df, regime_col, include_self_transitions=False):
    enriched = df.copy()
    enriched["prev_regime"] = enriched[regime_col].shift(1)
    enriched["curr_regime"] = enriched[regime_col]
    enriched["transition"] = (
        enriched["prev_regime"].fillna("START") + " -> " + enriched["curr_regime"].fillna("NA")
    )

    mask = enriched["prev_regime"].notna() & enriched["curr_regime"].notna()
    if not include_self_transitions:
        mask &= enriched["prev_regime"] != enriched["curr_regime"]
    return enriched.loc[mask].copy()


def ordered_transition_names(transitions):
    preferred = []
    for from_regime in REGIME_ORDER:
        for to_regime in REGIME_ORDER:
            if from_regime == to_regime:
                continue
            name = f"{from_regime} -> {to_regime}"
            if name in transitions:
                preferred.append(name)
    extras = sorted(name for name in transitions if name not in preferred)
    return preferred + extras


def build_transition_summary(events, horizons):
    rows = []
    transitions = ordered_transition_names(events["transition"].dropna().unique())

    for transition_name in transitions:
        data = events.loc[events["transition"] == transition_name]
        from_regime, to_regime = transition_name.split(" -> ", 1)
        for horizon in horizons:
            col = f"forward_return_{horizon}d"
            series = data[col].dropna()
            rows.append(
                {
                    "group": transition_name,
                    "mode": "transition",
                    "horizon_days": horizon,
                    "samples": int(series.shape[0]),
                    "mean_return": float(series.mean()) if len(series) else np.nan,
                    "median_return": float(series.median()) if len(series) else np.nan,
                    "std_return": float(series.std()) if len(series) else np.nan,
                    "win_rate": float((series > 0).mean()) if len(series) else np.nan,
                    "q25_return": float(series.quantile(0.25)) if len(series) else np.nan,
                    "q75_return": float(series.quantile(0.75)) if len(series) else np.nan,
                    "from_regime": from_regime,
                    "to_regime": to_regime,
                    "transition": transition_name,
                }
            )

    summary = pd.DataFrame(rows)
    rank = {name: idx for idx, name in enumerate(transitions)}
    summary["_group_rank"] = summary["group"].map(lambda x: rank.get(x, 999))
    summary = summary.sort_values(["_group_rank", "horizon_days"]).drop(columns="_group_rank")
    return summary.reset_index(drop=True)


def print_summary(summary, bar_lookup, mode):
    title = "Regime Forward Return Analysis" if mode == "regime" else "Transition Forward Return Analysis"
    print("\n" + "=" * 72)
    print(title)
    print("=" * 72)
    print("Horizon to bar mapping:")
    for horizon, bars in bar_lookup.items():
        print(f"  {horizon:>3d}d -> {bars} bars")

    for group_name in summary["group"].drop_duplicates():
        block = summary.loc[summary["group"] == group_name]
        if block.empty:
            continue
        print(f"\n[{group_name}]")
        for _, row in block.iterrows():
            mean_pct = row["mean_return"] * 100 if pd.notna(row["mean_return"]) else np.nan
            median_pct = row["median_return"] * 100 if pd.notna(row["median_return"]) else np.nan
            win_pct = row["win_rate"] * 100 if pd.notna(row["win_rate"]) else np.nan
            print(
                f"  +{int(row['horizon_days']):>3d}d | n={int(row['samples']):>5d} | "
                f"mean={mean_pct:>7.2f}% | median={median_pct:>7.2f}% | win={win_pct:>6.1f}%"
            )


def save_outputs(summary, output_paths, mode):
    ensure_parent_dir(output_paths["summary"])
    ensure_parent_dir(output_paths["detail"])
    summary.to_csv(output_paths["detail"], index=False)

    mean_pivot = summary.pivot(index="group", columns="horizon_days", values="mean_return")
    mean_pivot.columns = [f"mean_return_{int(col)}d" for col in mean_pivot.columns]

    win_pivot = summary.pivot(index="group", columns="horizon_days", values="win_rate")
    win_pivot.columns = [f"win_rate_{int(col)}d" for col in win_pivot.columns]

    samples_pivot = summary.pivot(index="group", columns="horizon_days", values="samples")
    samples_pivot.columns = [f"samples_{int(col)}d" for col in samples_pivot.columns]

    if mode == "transition":
        meta = summary[["group", "from_regime", "to_regime"]].drop_duplicates().set_index("group")
        combined = meta.join(mean_pivot).join(win_pivot).join(samples_pivot).reset_index()
    else:
        combined = mean_pivot.join(win_pivot).join(samples_pivot).reset_index()

    combined.to_csv(output_paths["summary"], index=False)


def plot_regime_summary(summary, output_path):
    plot_df = summary.loc[summary["group"] != "All"].copy()
    if plot_df.empty:
        return

    ordered_groups = [name for name in REGIME_ORDER if name in plot_df["group"].unique()]
    mean_matrix = plot_df.pivot(index="group", columns="horizon_days", values="mean_return").reindex(ordered_groups)
    win_matrix = plot_df.pivot(index="group", columns="horizon_days", values="win_rate").reindex(ordered_groups)

    fig, axes = plt.subplots(2, 1, figsize=(9, 7.5))

    sns.heatmap(
        mean_matrix * 100,
        annot=True,
        fmt=".2f",
        cmap="RdYlGn",
        center=0,
        cbar_kws={"label": "Mean forward return (%)"},
        ax=axes[0],
    )
    axes[0].set_title("Forward Mean Return by Current Regime")
    axes[0].set_xlabel("Horizon (days)")
    axes[0].set_ylabel("Regime")

    sns.heatmap(
        win_matrix * 100,
        annot=True,
        fmt=".1f",
        cmap="YlGn",
        vmin=0,
        vmax=100,
        cbar_kws={"label": "Win rate (%)"},
        ax=axes[1],
    )
    axes[1].set_title("Positive Return Frequency by Current Regime")
    axes[1].set_xlabel("Horizon (days)")
    axes[1].set_ylabel("Regime")

    plt.tight_layout()
    ensure_parent_dir(output_path)
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()


def plot_transition_summary(summary, output_path):
    if summary.empty:
        return

    mean_matrix = summary.pivot(index="group", columns="horizon_days", values="mean_return")
    win_matrix = summary.pivot(index="group", columns="horizon_days", values="win_rate")
    sample_matrix = summary.pivot(index="group", columns="horizon_days", values="samples")
    ordered_groups = summary["group"].drop_duplicates().tolist()
    mean_matrix = mean_matrix.reindex(ordered_groups)
    win_matrix = win_matrix.reindex(ordered_groups)
    sample_matrix = sample_matrix.reindex(ordered_groups)

    mean_annot = pd.DataFrame("", index=mean_matrix.index, columns=mean_matrix.columns, dtype=object)
    win_annot = pd.DataFrame("", index=win_matrix.index, columns=win_matrix.columns, dtype=object)
    for idx in mean_matrix.index:
        for col in mean_matrix.columns:
            samples = sample_matrix.loc[idx, col]
            if pd.isna(mean_matrix.loc[idx, col]):
                continue
            mean_annot.loc[idx, col] = f"{mean_matrix.loc[idx, col] * 100:.2f}%\n(n={int(samples)})"
            win_annot.loc[idx, col] = f"{win_matrix.loc[idx, col] * 100:.1f}%\n(n={int(samples)})"

    fig, axes = plt.subplots(2, 1, figsize=(10, max(7, len(ordered_groups) * 0.7 + 2)))

    sns.heatmap(
        mean_matrix * 100,
        annot=mean_annot,
        fmt="",
        cmap="RdYlGn",
        center=0,
        cbar_kws={"label": "Mean forward return (%)"},
        ax=axes[0],
    )
    axes[0].set_title("Forward Mean Return by Transition Event")
    axes[0].set_xlabel("Horizon (days)")
    axes[0].set_ylabel("Transition")

    sns.heatmap(
        win_matrix * 100,
        annot=win_annot,
        fmt="",
        cmap="YlGn",
        vmin=0,
        vmax=100,
        cbar_kws={"label": "Win rate (%)"},
        ax=axes[1],
    )
    axes[1].set_title("Positive Return Frequency by Transition Event")
    axes[1].set_xlabel("Horizon (days)")
    axes[1].set_ylabel("Transition")

    plt.tight_layout()
    ensure_parent_dir(output_path)
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()


def plot_summary(summary, output_path, mode):
    if mode == "regime":
        plot_regime_summary(summary, output_path)
    else:
        plot_transition_summary(summary, output_path)


def main():
    args = parse_args()
    df = load_prediction_frame(args.input)

    required_cols = [args.price_col, args.regime_col]
    missing = [col for col in required_cols if col not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {', '.join(missing)}")

    bars_per_day = args.bars_per_day if args.bars_per_day is not None else infer_bars_per_day(df, args.datetime_col)
    enriched, bar_lookup = add_forward_return_columns(df, args.price_col, args.horizons, bars_per_day)

    event_count = None
    if args.mode == "regime":
        summary = build_regime_summary(enriched, args.regime_col, args.horizons)
    else:
        events = build_transition_events(enriched, args.regime_col, args.include_self_transitions)
        event_count = len(events)
        summary = build_transition_summary(events, args.horizons)

    output_paths = resolve_output_paths(args.mode, args.output_prefix)
    print_summary(summary, bar_lookup, args.mode)
    save_outputs(summary, output_paths, args.mode)
    plot_summary(summary, output_paths["plot"], args.mode)

    if args.mode == "transition":
        print(f"\nTotal transition events analyzed: {event_count if event_count is not None else 0}")
    print(f"Saved summary CSV to {output_paths['summary']}")
    print(f"Saved detail CSV to {output_paths['detail']}")
    print(f"Saved plot to {output_paths['plot']}")


if __name__ == "__main__":
    main()
